<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GameVersion Condition=" '$(GameVersion)' == '' ">1.6</GameVersion>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>RimMind.Presentation</RootNamespace>
    <AssemblyName>2_RimMindCore</AssemblyName>
    <Version>2.0.0</Version>
    <OutputPath>..\$(GameVersion)\Assemblies\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>CS8604;CS8601;CS8602;CS8603</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);V$(GameVersion.Replace('.', '_'))</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include=".\Application\RimMindCore.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="$(GameVersion).*-*" PrivateAssets="All" />
    <PackageReference Include="Lib.Harmony.Ref" Version="2.*" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.*" PrivateAssets="All" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>RimMindCore.Integration.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AICoreMod.cs" />
    <Compile Include="RimMindAPI.cs" />
    <Compile Include="Infrastructure\**\*.cs" />
    <Compile Include="Presentation\**\*.cs" />
    <Compile Remove="Presentation\Agent\Modes\**\*.cs" />
  </ItemGroup>

</Project>
