using System;
using Xunit;

namespace RimMind.Tests.Domain.Llm
{
    public class LlmRequestEnvelopeBuilderTests
    {
        [Fact]
        public void Build_WithoutScenarioId_ThrowsInvalidOperationException()
        {
            var builder = new LlmRequestEnvelopeBuilder();

            Assert.Throws<InvalidOperationException>(() => builder.Build());
        }

        [Fact]
        public void ForScenarioId_Build_GeneratesCorrectDefaults()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .Build();

            Assert.Equal("scenario1", envelope.ScenarioId);
            Assert.Equal(800, envelope.MaxTokens);
            Assert.Equal(0.7f, envelope.Temperature);
            Assert.Equal(AIRequestPriority.Normal, envelope.Priority);
        }

        [Fact]
        public void ForNpc_SetsNpcIdAndGameStateInfo()
        {
            var envelope = LlmRequestEnvelopeBuilder.ForNpc("npc42", new GameStateInfo().AddSection("perceptions", "gameState"))
                .ForScenarioId("scenario1")
                .Build();

            Assert.Equal("npc42", envelope.NpcId);
            Assert.NotNull(envelope.GameStateInfo);
            Assert.Contains("gameState", envelope.GameStateInfo.ToXml());
        }

        [Fact]
        public void WithMaxTokens_OverridesDefault()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .WithMaxTokens(1600)
                .Build();

            Assert.Equal(1600, envelope.MaxTokens);
        }

        [Fact]
        public void WithTemperature_OverridesDefault()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .WithTemperature(0.3f)
                .Build();

            Assert.Equal(0.3f, envelope.Temperature);
        }

        [Fact]
        public void WithPriority_OverridesDefault()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .WithPriority(AIRequestPriority.High)
                .Build();

            Assert.Equal(AIRequestPriority.High, envelope.Priority);
        }

        [Fact]
        public void WithModId_SetsExplicitValue()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .WithModId("MyMod")
                .Build();

            Assert.Equal("MyMod", envelope.ModId);
        }

        [Fact]
        public void ModId_NotSet_FallsBackToScenarioId()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .Build();

            Assert.Equal("scenario1", envelope.ModId);
        }

        [Fact]
        public void Streaming_SetsIsStreamingTrue()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .Streaming(_ => { })
                .Build();

            Assert.True(envelope.IsStreaming);
        }

        [Fact]
        public void TraceId_AutoGenerated_Length12()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .Build();

            Assert.NotNull(envelope.TraceId);
            Assert.Equal(12, envelope.TraceId.Length);
        }

        [Fact]
        public void RequestId_AutoGenerated_NonEmpty()
        {
            var envelope = new LlmRequestEnvelopeBuilder()
                .ForScenarioId("scenario1")
                .Build();

            Assert.False(string.IsNullOrEmpty(envelope.RequestId));
        }
    }
}
